services:
  digital-plant-db-sql:
    image: postgres:15.3-alpine
    container_name: test-db-container
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -D test"]
      interval: 5s
      timeout: 2s
      retries: 25
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data
    command: [  "postgres", "-c", "max_connections=400" ]

volumes:
  db_test_data: { }
